# Generated by Django 4.1.13 on 2026-01-01 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('media_type', models.CharField(choices=[('pdf', 'Document PDF'), ('video', 'Vidéo'), ('mixed', 'Mixte (PDF + Vidéo)')], default='pdf', help_text='Type principal du contenu', max_length=10)),
                ('course_type', models.CharField(choices=[('free', 'Gratuit'), ('paid', 'Payant')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20)),
                ('objectives', models.TextField(blank=True, help_text="Objectifs d'apprentissage")),
                ('prerequisites', models.TextField(blank=True, help_text='Prérequis')),
                ('target_audience', models.TextField(blank=True, help_text='Public cible')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Durée totale en heures (pour vidéos)')),
                ('pages', models.PositiveIntegerField(default=0, help_text='Nombre de pages (pour PDFs)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('cover_photo', models.ImageField(blank=True, help_text='Photo de couverture du cours', null=True, upload_to='course_covers/')),
                ('preview_video_url', models.URLField(blank=True, help_text='URL de la vidéo (YouTube, Vimeo, etc.)', null=True)),
                ('document_file', models.FileField(blank=True, help_text='Document PDF du cours', null=True, upload_to='course_documents/')),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('instructor_id', models.IntegerField()),
                ('instructor_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='Français', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('certificate_available', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'published_at'], name='courses_cou_status_96f2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'course_type'], name='courses_cou_categor_8cc0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor_id'], name='courses_cou_instruc_d2e347_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['media_type'], name='courses_cou_media_t_c66401_idx'),
        ),
    ]
