# Generated by Django 4.1.13 on 2026-01-03 20:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text="ID de l'utilisateur depuis le serveur d'authentification")),
                ('user_username', models.CharField(blank=True, max_length=150)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_full_name', models.CharField(blank=True, max_length=255)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment_type', models.CharField(choices=[('free', 'Gratuit'), ('paid', 'Payant')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('dropped', 'Abandonné')], default='not_started', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progression en pourcentage (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('access_code', models.CharField(blank=True, help_text="Code d'accès unique pour l'étudiant", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes personnelles sur le cours')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synchronisé'), ('pending', 'En attente'), ('failed', 'Échoué')], default='synced', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user_id', 'status'], name='courses_enr_user_id_ce8b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'user_id'], name='courses_enr_course__ba0273_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_date'], name='courses_enr_enrollm_eb8905_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['last_accessed'], name='courses_enr_last_ac_514789_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status', 'progress'], name='courses_enr_status_cff774_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user_id', 'course')},
        ),
    ]
