# Generated by Django 4.2.16 on 2026-01-04 08:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID Utilisateur')),
                ('method_type', models.CharField(choices=[('rib', 'RIB'), ('card', 'Carte bancaire')], max_length=10, verbose_name='Type de méthode')),
                ('rib_number', models.CharField(blank=True, max_length=27, null=True, verbose_name='Numéro RIB')),
                ('rib_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulaire')),
                ('rib_bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banque')),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True, verbose_name='4 derniers chiffres')),
                ('card_expiry_month', models.CharField(blank=True, max_length=2, null=True, verbose_name='Mois expiration')),
                ('card_expiry_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Année expiration')),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom sur la carte')),
                ('card_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type de carte')),
                ('is_default', models.BooleanField(default=False, verbose_name='Méthode par défaut')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'indexes': [models.Index(fields=['user_id', 'is_default'], name='payments_us_user_id_cf8041_idx'), models.Index(fields=['user_id', 'method_type'], name='payments_us_user_id_255b10_idx')],
                'unique_together': {('user_id', 'rib_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID Transaction')),
                ('user_id', models.IntegerField(verbose_name='ID Utilisateur')),
                ('course_id', models.IntegerField(default=0, verbose_name='ID Cours')),
                ('course_name', models.CharField(default='Cours', max_length=255, verbose_name='Nom du cours')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('rib', 'RIB'), ('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('free', 'Gratuit')], default='rib', max_length=20, verbose_name='Méthode de paiement')),
                ('rib_number', models.CharField(blank=True, max_length=27, null=True, verbose_name='Numéro RIB')),
                ('rib_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulaire du compte')),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True, verbose_name='4 derniers chiffres')),
                ('card_expiry_month', models.CharField(blank=True, max_length=2, null=True, verbose_name="Mois d'expiration")),
                ('card_expiry_year', models.CharField(blank=True, max_length=4, null=True, verbose_name="Année d'expiration")),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom sur la carte')),
                ('access_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name="Code d'accès")),
                ('enrollment_code', models.CharField(blank=True, max_length=50, null=True, verbose_name="Code d'inscription")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('enrollment_status', models.CharField(choices=[('not_created', 'Inscription non créée'), ('created', 'Inscription créée'), ('failed', 'Échec inscription')], default='not_created', max_length=20, verbose_name='Statut inscription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transactions', to='payments.paymenttransaction', verbose_name='Transaction parente')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='payments_pa_user_id_92d873_idx'), models.Index(fields=['course_id', 'status'], name='payments_pa_course__a241eb_idx'), models.Index(fields=['access_code'], name='payments_pa_access__275d57_idx'), models.Index(fields=['created_at'], name='payments_pa_created_a246c6_idx'), models.Index(fields=['status', 'enrollment_status'], name='payments_pa_status_739c62_idx')],
            },
        ),
    ]
