# Generated by Django 4.1.13 on 2026-01-02 09:21

import authentication.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(default='etudiant', max_length=20, verbose_name="Type d'utilisateur")),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('photo_profil', models.ImageField(blank=True, help_text='Téléchargez une photo de profil (format recommandé: carré, max 2MB)', null=True, upload_to=authentication.models.user_profile_upload_path, verbose_name='Photo de profil')),
                ('pays', models.CharField(blank=True, choices=[('MA', 'Maroc'), ('FR', 'France'), ('BE', 'Belgique'), ('CA', 'Canada'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('SN', 'Sénégal'), ('CI', "Côte d'Ivoire"), ('OTHER', 'Autre pays')], default='MA', help_text='Sélectionnez votre pays de résidence', max_length=50, verbose_name='Pays')),
                ('langue', models.CharField(blank=True, choices=[('fr', 'Français'), ('ar', 'Arabe'), ('en', 'Anglais'), ('es', 'Espagnol'), ('de', 'Allemand'), ('OTHER', 'Autre langue')], default='fr', help_text='Sélectionnez votre langue préférée', max_length=20, verbose_name='Langue préférée')),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token API')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Refresh Token')),
                ('bio', models.TextField(blank=True, help_text='Présentez-vous en quelques mots', null=True, verbose_name='Biographie')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web personnel')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Profil LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Profil GitHub')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='authenticat_user_ty_277406_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pays'], name='authenticat_pays_977efe_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['langue'], name='authenticat_langue_c73b50_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='authenticat_date_jo_0d654e_idx'),
        ),
    ]
